FEEDIDS = "feed.ids:%s"
FEEDITEMS = "feed.items:%s"
FEEDPUB = "feed.publish:%s"
FEEDPUBD = "feed.published:%s"
FEEDPUBS = "feed.publishes:%s"
FEEDRETRACT = "feed.retract:%s"
FEEDCONFIG = "feed.config:%s"
FEEDEDIT = "feed.edit:%s"
FEEDCANCELLED = "feed.cancelled:%s"

FEEDJOBCLAIMED = "feed.claimed:%s"
FEEDJOBSTALLED = "feed.stalled:%s"
FEEDJOBFINISHED = "feed.finished:%s\x00%s"
FEEDJOBRUNNING = "feed.running:%s"

CONFFEED = "conffeed"
NEWFEED = "newfeed"
DELFEED = "delfeed"
JOBSTATS = "jobstats"

